-- ============================================
-- EXERCISE 1: Explore your schema
-- ============================================
-- List all the objects in your schema using user_objects
-- Group by object_type and count them
-- Which object types do you have?

-- "OBJECT_TYPE"	"CNT"
-- "INDEX"	        12
-- "LOB"	1
-- "PROCEDURE"	1
-- "SEQUENCE"	3
-- "TABLE"	11
-- "TRIGGER"	3


-- Sample solution:
SELECT object_type, COUNT(*) AS cnt
FROM user_objects
GROUP BY object_type
ORDER BY object_type;

-- Also get details:
SELECT object_name, object_type, created, last_ddl_time
FROM user_objects
ORDER BY object_type, object_name;

-- "OBJECT_NAME"	"OBJECT_TYPE"	"CREATED"	"LAST_DDL_TIME"
-- "IDX_VISIT_DATE"	"INDEX"	"2026-04-14T14:02:50Z"	"2026-04-14T14:02:50Z"
-- "SYS_C002420539"	"INDEX"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "SYS_C002420540"	"INDEX"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "SYS_C002420542"	"INDEX"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "SYS_C002420545"	"INDEX"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "SYS_C002824493"	"INDEX"	"2026-03-24T14:27:56Z"	"2026-03-24T14:27:56Z"
-- "SYS_C003236592"	"INDEX"	"2026-04-07T14:01:03Z"	"2026-04-07T14:01:03Z"
-- "SYS_C003457958"	"INDEX"	"2026-04-14T13:51:32Z"	"2026-04-14T13:51:32Z"
-- "SYS_C003677093"	"INDEX"	"2026-04-21T13:58:14Z"	"2026-04-21T13:58:14Z"
-- "SYS_IL0002934135C00004$$"	"INDEX"	"2026-04-07T14:01:03Z"	"2026-04-07T14:01:03Z"
-- "UQ_ENROLLMENT"	"INDEX"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "select count(*) from bricks;_id_pk"	"INDEX"	"2026-03-03T14:14:32Z"	"2026-03-03T14:14:32Z"
-- "SYS_LOB0002934135C00004$$"	"LOB"	"2026-04-07T14:01:03Z"	"2026-04-07T14:01:03Z"
-- "DEPOSIT_FUNDS"	"PROCEDURE"	"2026-04-21T14:28:17Z"	"2026-04-21T14:28:17Z"
-- "ISEQ$$_2581988"	"SEQUENCE"	"2026-03-24T14:27:56Z"	"2026-03-24T14:27:56Z"
-- "ISEQ$$_2934135"	"SEQUENCE"	"2026-04-07T14:01:03Z"	"2026-04-07T14:01:03Z"
-- "ISEQ$$_3131552"	"SEQUENCE"	"2026-04-14T13:51:32Z"	"2026-04-14T13:51:32Z"
-- "ACCOUNTS"	"TABLE"	"2026-04-21T13:58:14Z"	"2026-04-21T13:58:14Z"
-- "BRICKS"	"TABLE"	"2026-03-03T14:14:05Z"	"2026-03-03T14:14:05Z"
-- "COURSES"	"TABLE"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "DOC_CHUNKS"	"TABLE"	"2026-04-07T14:01:03Z"	"2026-04-07T14:01:03Z"
-- "MY_BRICK_COLLECTION"	"TABLE"	"2026-03-10T13:20:47Z"	"2026-03-10T13:20:47Z"
-- "PATIENT_VISITS"	"TABLE"	"2026-04-14T13:51:32Z"	"2026-04-14T14:33:56Z"
-- "PET_CARE_LOG"	"TABLE"	"2026-03-24T14:27:56Z"	"2026-03-24T14:37:01Z"
-- "STUDENTS"	"TABLE"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "STUDENT_COURSES"	"TABLE"	"2026-03-03T14:00:30Z"	"2026-03-03T14:00:30Z"
-- "YOUR_BRICK_COLLECTION"	"TABLE"	"2026-03-10T13:20:47Z"	"2026-03-10T13:20:47Z"
-- "select count(*) from bricks;"	"TABLE"	"2026-03-03T14:14:32Z"	"2026-03-03T14:14:32Z"
-- "TRIGGER_DELETELOG"	"TRIGGER"	"2026-03-24T14:37:01Z"	"2026-03-24T14:37:01Z"
-- "TRIGGER_INSERTLOG"	"TRIGGER"	"2026-03-24T14:27:56Z"	"2026-03-24T14:36:04Z"
-- "TRIGGER_UPDATELOG"	"TRIGGER"	"2026-03-24T14:36:57Z"	"2026-03-24T14:36:57Z"

-- ============================================
-- EXERCISE 2: Basic GET_DDL
-- ============================================
-- First, set transform params for clean output:
BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

SET LONG 100000
SET PAGESIZE 0

-- Get DDL for one of your tables (replace MY_TABLE with actual name)
SELECT DBMS_METADATA.GET_DDL('TABLE', 'MY_TABLE') FROM DUAL;

-- Identify the key parts in the output:
--   - Column definitions (NAME, TYPE, NULL/NOT NULL)
--   - Constraints (PRIMARY KEY, FK, CHECK)
--   - Storage parameters (if included)

/** "DBMS_METADATA.GET_DDL('TABLE','STUDENTS')"
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""STUDENTS""  // Table name and schema
   (	""STUDENT_ID"" NUMBER,  // Name of variable with its type
	""FIRST_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""LAST_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""EMAIL"" VARCHAR2(100) NOT NULL ENABLE, 
	""ENROLL_DATE"" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY (""STUDENT_ID"") // Primary key definition
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 // Storage Parameters
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE, 
	 UNIQUE (""EMAIL"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" " **/

-- Or get all tables at once:
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
ORDER BY table_name;

-- ============================================
-- EXERCISE 3: Clean DDL for portability
-- ============================================
-- Remove schema names from DDL so it works in any schema

BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'EMIT_SCHEMA', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

-- Compare the output with and without EMIT_SCHEMA:
-- With EMIT_SCHEMA (default):   CREATE TABLE "SALES"."ORDERS" ...
-- Without EMIT_SCHEMA:          CREATE TABLE "ORDERS" ...
-- In this case the output where not different but the one without emit should not show the current schema

-- Try it yourself:
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
WHERE ROWNUM = 1;

/** 
With Emit schema
"DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME)"
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""ACCOUNTS"" 
   (	""ACCOUNT_ID"" NUMBER, 
	""OWNER_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""BALANCE"" NUMBER(10,2) NOT NULL ENABLE, 
	 CHECK (balance >= 0) ENABLE, 
	 PRIMARY KEY (""ACCOUNT_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "

**/

/** 
Without Schema
"DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME)"
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""ACCOUNTS"" 
   (	""ACCOUNT_ID"" NUMBER, 
	""OWNER_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""BALANCE"" NUMBER(10,2) NOT NULL ENABLE, 
	 CHECK (balance >= 0) ENABLE, 
	 PRIMARY KEY (""ACCOUNT_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
**/


-- ============================================
-- EXERCISE 4: Plan a migration
-- ============================================
-- Note: I do not have any table with foreign key soo the order in the migration does not matter


-- You're moving to a new schema with a different name.
-- What changes would you need to make to your exported DDL?
-- We should change the schema name in the backup

-- Scenario: Migrating from SCHEMA_OLD to SCHEMA_NEW

-- 1. First, identify schema names embedded in your DDL:
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
WHERE table_name = 'ANY_TABLE_WITH_FK';

-- 2. Check for schema-qualified references:
SELECT constraint_name, table_name, r_constraint_name
FROM user_constraints
WHERE constraint_type = 'R';

-- 3. If you find FK constraints pointing to other schemas, you need to:
--    - Update the REFERENCES clause to point to new schema name
--    - Or make sure target table exists in same schema

-- 4. Write a migration checklist:
--    □ Export all DDL with EMIT_SCHEMA = false
--    □ Review FK constraints for schema references
--    □ Update constraint references if needed
--    □ Reload in order: tables → constraints → indexes → views → code
BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'EMIT_SCHEMA', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
ORDER BY table_name;


-- ============================================
-- EXERCISE 5: Dependency order
-- ============================================
-- Look at user_dependencies to understand object relationships

-- See all dependencies in your schema:
SELECT referenced_name, referencing_name, referencing_type
FROM user_dependencies
ORDER BY referenced_name;

/**
"REFERENCING_NAME"	"REFERENCING_TYPE"	"REFERENCED_NAME"	"REFERENCED_TYPE"
"DEPOSIT_FUNDS"	"PROCEDURE"	"ACCOUNTS"	"TABLE"
"TRIGGER_INSERTLOG"	"TRIGGER"	"DBMS_STANDARD"	"PACKAGE"
"TRIGGER_UPDATELOG"	"TRIGGER"	"DBMS_STANDARD"	"PACKAGE"
"TRIGGER_DELETELOG"	"TRIGGER"	"DBMS_STANDARD"	"PACKAGE"
"DEPOSIT_FUNDS"	"PROCEDURE"	"DBMS_STANDARD"	"PACKAGE"
"TRIGGER_INSERTLOG"	"TRIGGER"	"PET_CARE_LOG"	"TABLE"
"TRIGGER_UPDATELOG"	"TRIGGER"	"PET_CARE_LOG"	"TABLE"
"TRIGGER_DELETELOG"	"TRIGGER"	"PET_CARE_LOG"	"TABLE"
"DEPOSIT_FUNDS"	"PROCEDURE"	"STANDARD"	"PACKAGE"
"TRIGGER_UPDATELOG"	"TRIGGER"	"STANDARD"	"PACKAGE"
"TRIGGER_INSERTLOG"	"TRIGGER"	"STANDARD"	"PACKAGE"
"TRIGGER_DELETELOG"	"TRIGGER"	"STANDARD"	"PACKAGE"
"DEPOSIT_FUNDS"	"PROCEDURE"	"SYS_STUB_FOR_PURITY_ANALYSIS"	"PACKAGE"

*/


-- Find objects that depend on TABLES (to know what needs tables first):
SELECT referencing_name, referencing_type
FROM user_dependencies
WHERE referenced_name IN (
  SELECT table_name FROM user_tables
)
ORDER BY referencing_type, referencing_name;

/**
"REFERENCING_NAME"	"REFERENCING_TYPE"
"DEPOSIT_FUNDS"	"PROCEDURE"
"TRIGGER_DELETELOG"	"TRIGGER"
"TRIGGER_INSERTLOG"	"TRIGGER"
"TRIGGER_UPDATELOG"	"TRIGGER"
*/

-- Find direct dependencies for a specific object (replace PROC_NAME):
SELECT referenced_name, referenced_type
FROM user_dependencies
WHERE referencing_name = 'PROC_NAME';
/**
Proc DEPOSIT_FUNDS
"REFERENCED_NAME"	"REFERENCED_TYPE"
"STANDARD"	"PACKAGE"
"DBMS_STANDARD"	"PACKAGE"
"SYS_STUB_FOR_PURITY_ANALYSIS"	"PACKAGE"
"ACCOUNTS"	"TABLE"

Proc TRIGGER_DELETELOG
"REFERENCED_NAME"	"REFERENCED_TYPE"
"STANDARD"	"PACKAGE"
"DBMS_STANDARD"	"PACKAGE"
"PET_CARE_LOG"	"TABLE"

Proc TRIGGER_INSERTLOG
"REFERENCED_NAME"	"REFERENCED_TYPE"
"STANDARD"	"PACKAGE"
"DBMS_STANDARD"	"PACKAGE"
"PET_CARE_LOG"	"TABLE"

Proc TRIGGER_UPDATELOG
"REFERENCED_NAME"	"REFERENCED_TYPE"
"STANDARD"	"PACKAGE"
"DBMS_STANDARD"	"PACKAGE"
"PET_CARE_LOG"	"TABLE"
*/


-- Build a dependency tree for PL/SQL objects:
SELECT referencing_name, referencing_type,
       LISTAGG(referenced_name, ', ') WITHIN GROUP (ORDER BY referenced_name) AS dependencies
FROM user_dependencies
WHERE referencing_type IN ('PACKAGE', 'PROCEDURE', 'FUNCTION')
GROUP BY referencing_name, referencing_type
ORDER BY referencing_type, referencing_name;

/**
"REFERENCING_NAME"	"REFERENCING_TYPE"	"DEPENDENCIES"
"DEPOSIT_FUNDS"	"PROCEDURE"	"ACCOUNTS, DBMS_STANDARD, STANDARD, SYS_STUB_FOR_PURITY_ANALYSIS"
*/

-- ============================================
-- EXERCISE 6: Design your own backup strategy
-- ============================================
-- Given:
--   - No expdp access (no directory privileges)
--   - Need to move your schema to another database
--   - Only have SQL access
--
-- Design the steps you would take:

-- STEP 1: Document your current schema structure
SELECT object_type, COUNT(*) FROM user_objects GROUP BY object_type;
SELECT table_name, num_rows FROM user_tables ORDER BY num_rows DESC;

/**
"OBJECT_TYPE"	"COUNT(*)"
"TABLE"	11
"PROCEDURE"	1
"INDEX"	12
"SEQUENCE"	3
"LOB"	1
"TRIGGER"	3
*/


-- STEP 2: Extract all DDL (run all these)
BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

-- Extract tables (spool to file or copy output):
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name) FROM user_tables;
/**
"DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME)"
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""ACCOUNTS"" 
   (	""ACCOUNT_ID"" NUMBER, 
	""OWNER_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""BALANCE"" NUMBER(10,2) NOT NULL ENABLE, 
	 CHECK (balance >= 0) ENABLE, 
	 PRIMARY KEY (""ACCOUNT_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""BRICKS"" 
   (	""BRICK_ID"" NUMBER(*,0), 
	""COLOUR"" VARCHAR2(10), 
	""SHAPE"" VARCHAR2(10), 
	""WEIGHT"" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""COURSES"" 
   (	""COURSE_ID"" NUMBER, 
	""COURSE_NAME"" VARCHAR2(100) NOT NULL ENABLE, 
	""INSTRUCTOR"" VARCHAR2(100), 
	""CREDITS"" NUMBER(1,0), 
	 PRIMARY KEY (""COURSE_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""DOC_CHUNKS"" 
   (	""CHUNK_ID"" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	""DOC_NAME"" VARCHAR2(200), 
	""CHUNK_TEXT"" VARCHAR2(2000), 
	""CHUNK_VECTOR"" VECTOR(384, FLOAT32), 
	 PRIMARY KEY (""CHUNK_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" 
 VECTOR (""CHUNK_VECTOR"") STORE AS (
  TABLESPACE ""USERS""  CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""MY_BRICK_COLLECTION"" 
   (	""COLOUR"" VARCHAR2(10), 
	""SHAPE"" VARCHAR2(10), 
	""WEIGHT"" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""PATIENT_VISITS"" 
   (	""VISIT_ID"" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	""PATIENT_ID"" NUMBER NOT NULL ENABLE, 
	""SITE_ID"" NUMBER NOT NULL ENABLE, 
	""VISIT_DATE"" DATE NOT NULL ENABLE, 
	""STATUS"" VARCHAR2(20) NOT NULL ENABLE, 
	""DIAGNOSIS"" VARCHAR2(100), 
	""AMOUNT_USD"" NUMBER(10,2), 
	 PRIMARY KEY (""VISIT_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""PET_CARE_LOG"" 
   (	""PRODUCT_ID"" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	""CREATED_BY_USER"" VARCHAR2(30), 
	""LOG_TEXT"" VARCHAR2(500), 
	""LAST_UPDATE_DATETIME"" DATE, 
	""UPDATE_DATE"" DATE, 
	""UPDATED_BY_USER"" VARCHAR2(30), 
	 PRIMARY KEY (""PRODUCT_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""STUDENTS"" 
   (	""STUDENT_ID"" NUMBER, 
	""FIRST_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""LAST_NAME"" VARCHAR2(50) NOT NULL ENABLE, 
	""EMAIL"" VARCHAR2(100) NOT NULL ENABLE, 
	""ENROLL_DATE"" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY (""STUDENT_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE, 
	 UNIQUE (""EMAIL"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""STUDENT_COURSES"" 
   (	""SC_ID"" NUMBER, 
	""STUDENT_ID"" NUMBER NOT NULL ENABLE, 
	""COURSE_ID"" NUMBER NOT NULL ENABLE, 
	""GRADE"" VARCHAR2(2), 
	 PRIMARY KEY (""SC_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE, 
	 CONSTRAINT ""UQ_ENROLLMENT"" UNIQUE (""STUDENT_ID"", ""COURSE_ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS""  ENABLE, 
	 CONSTRAINT ""FK_STUDENT"" FOREIGN KEY (""STUDENT_ID"")
	  REFERENCES ""A01644488_SCHEMA_TRPB0"".""STUDENTS"" (""STUDENT_ID"") ENABLE, 
	 CONSTRAINT ""FK_COURSE"" FOREIGN KEY (""COURSE_ID"")
	  REFERENCES ""A01644488_SCHEMA_TRPB0"".""COURSES"" (""COURSE_ID"") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""YOUR_BRICK_COLLECTION"" 
   (	""HEIGHT"" NUMBER(*,0), 
	""WIDTH"" NUMBER(*,0), 
	""DEPTH"" NUMBER(*,0), 
	""COLOUR"" VARCHAR2(10), 
	""SHAPE"" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE TABLE ""A01644488_SCHEMA_TRPB0"".""select count(*) from bricks;"" 
   (	""ID"" NUMBER DEFAULT ON NULL to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL ENABLE, 
	 CONSTRAINT ""select count(*) from bricks;_id_pk"" PRIMARY KEY (""ID"")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ""USERS""  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE ""USERS"" "
*/

-- Extract indexes:
SELECT DBMS_METADATA.GET_DDL('INDEX', index_name) FROM user_indexes;

/**
"DBMS_METADATA.GET_DDL('INDEX',INDEX_NAME)"
"
  CREATE INDEX ""A01644488_SCHEMA_TRPB0"".""IDX_VISIT_DATE"" ON ""A01644488_SCHEMA_TRPB0"".""PATIENT_VISITS"" (""VISIT_DATE"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C002420539"" ON ""A01644488_SCHEMA_TRPB0"".""STUDENTS"" (""STUDENT_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C002420540"" ON ""A01644488_SCHEMA_TRPB0"".""STUDENTS"" (""EMAIL"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C002420542"" ON ""A01644488_SCHEMA_TRPB0"".""COURSES"" (""COURSE_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C002420545"" ON ""A01644488_SCHEMA_TRPB0"".""STUDENT_COURSES"" (""SC_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C002824493"" ON ""A01644488_SCHEMA_TRPB0"".""PET_CARE_LOG"" (""PRODUCT_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C003236592"" ON ""A01644488_SCHEMA_TRPB0"".""DOC_CHUNKS"" (""CHUNK_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C003457958"" ON ""A01644488_SCHEMA_TRPB0"".""PATIENT_VISITS"" (""VISIT_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_C003677093"" ON ""A01644488_SCHEMA_TRPB0"".""ACCOUNTS"" (""ACCOUNT_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""SYS_IL0002934135C00004$$"" ON ""A01644488_SCHEMA_TRPB0"".""DOC_CHUNKS"" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" 
  PARALLEL (DEGREE 0 INSTANCES 0) "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""UQ_ENROLLMENT"" ON ""A01644488_SCHEMA_TRPB0"".""STUDENT_COURSES"" (""STUDENT_ID"", ""COURSE_ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE ""USERS"" "
"
  CREATE UNIQUE INDEX ""A01644488_SCHEMA_TRPB0"".""select count(*) from bricks;_id_pk"" ON ""A01644488_SCHEMA_TRPB0"".""select count(*) from bricks;"" (""ID"") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE ""USERS"" "
*/

-- Extract views:
SELECT DBMS_METADATA.GET_DDL('VIEW', view_name) FROM user_views;
-- No tengo ninguna vista

-- Extract sequences:
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', sequence_name) FROM user_sequences;
-- Error


-- Extract constraints:
SELECT DBMS_METADATA.GET_DDL('CONSTRAINT', constraint_name) FROM user_constraints;
-- -- Error

-- Extract code:
SELECT DBMS_METADATA.GET_DDL('PROCEDURE', object_name) FROM user_objects WHERE object_type = 'PROCEDURE';
SELECT DBMS_METADATA.GET_DDL('FUNCTION', object_name) FROM user_objects WHERE object_type = 'FUNCTION';
SELECT DBMS_METADATA.GET_DDL('PACKAGE', object_name) FROM user_objects WHERE object_type = 'PACKAGE';

/**
"DBMS_METADATA.GET_DDL('PROCEDURE',OBJECT_NAME)"
"
  CREATE OR REPLACE EDITIONABLE PROCEDURE ""A01644488_SCHEMA_TRPB0"".""DEPOSIT_FUNDS"" (
    p_account_id NUMBER,
    p_amount NUMBER
)
AS
BEGIN
    IF p_amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invalid amount');
    END IF;

    UPDATE ACCOUNTS
    SET balance = balance + p_amount
    WHERE account_id = p_account_id;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
"
*/



-- STEP 3: Reload in new schema (use proper order)
-- 1. Create tables (no constraints yet)
-- 2. Create sequences
-- 3. Create indexes
-- 4. Add constraints (enable FKs)
-- 5. Create views
-- 6. Create procedures/functions/packages
-- 7. Create triggers

-- STEP 4: Verify everything transferred
SELECT object_type, COUNT(*) FROM user_objects GROUP BY object_type;
/**
"OBJECT_TYPE"	"COUNT(*)"
"TABLE"	11
"PROCEDURE"	1
"INDEX"	12
"SEQUENCE"	3
"LOB"	1
"TRIGGER"	3

*/


SELECT table_name, num_rows FROM user_tables ORDER BY table_name;
/**
"TABLE_NAME"	"NUM_ROWS"
"ACCOUNTS"	3
"BRICKS"	
"COURSES"	5
"DOC_CHUNKS"	20
"MY_BRICK_COLLECTION"	5
"PATIENT_VISITS"	50000
"PET_CARE_LOG"	
"STUDENTS"	6
"STUDENT_COURSES"	8
"YOUR_BRICK_COLLECTION"	3
"select count(*) from bricks;"	
*/


SELECT index_name, table_name FROM user_indexes ORDER BY index_name;

/**
"INDEX_NAME"	"TABLE_NAME"
"IDX_VISIT_DATE"	"PATIENT_VISITS"
"SYS_C002420539"	"STUDENTS"
"SYS_C002420540"	"STUDENTS"
"SYS_C002420542"	"COURSES"
"SYS_C002420545"	"STUDENT_COURSES"
"SYS_C002824493"	"PET_CARE_LOG"
"SYS_C003236592"	"DOC_CHUNKS"
"SYS_C003457958"	"PATIENT_VISITS"
"SYS_C003677093"	"ACCOUNTS"
"SYS_IL0002934135C00004$$"	"DOC_CHUNKS"
"UQ_ENROLLMENT"	"STUDENT_COURSES"
"select count(*) from bricks;_id_pk"	"select count(*) from bricks;"

*/


-- Q1: What are the limitations of DBMS_METADATA vs expdp?
-- A:  DBMS_METADATA only exports DDL (no data), requires manual spool/cursor,
--     and can't handle very large schemas easily.
--     expdp is faster, can export data, handles large schemas, but needs directory access.
--     Choose DBMS_METADATA when you have no DBA access or need educational visibility.
--     Choose expdp when you have proper access and need speed/completeness.

-- Q2: If you have circular dependencies (A depends on B, B depends on A),
--     how would you handle the reload?
-- A:  Oracle handles most circular dependencies automatically if you create
--     objects first and enable constraints later.
--     For PL/SQL circular dependencies, create the package/spec first,
--     then the package/body second.
--     DBMS_METADATA returns objects in a valid order - trust the dependency analysis.

-- Q3: Your company is migrating from one Oracle database to another.
--     They give you read-only access to the old database and want you
--     to recreate the schema on the new database.
--     What's your plan?
-- A:  1. Document source schema structure (user_objects, user_tables, etc.)
--     2. Set EMIT_SCHEMA=false and extract clean DDL
--     3. Check for dependencies and schema-qualified references
--     4. Review and clean up the DDL (remove storage, fix schema names)
--     5. Create new schema user on target
--     6. Run DDL in proper order (tables → constraints → indexes → views → code)
--     7. Verify with object counts and sample queries
--     8. If possible, export sample data via INSERT statements or CSV