--Create Table
Create table PET_CARE_LOG(
    PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE,
    UPDATE_DATE DATE,
    UPDATED_BY_USER VARCHAR2(30)
);

--Insert Log
CREATE OR REPLACE TRIGGER TRIGGER_InsertLog 
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.UPDATE_DATE := SYSDATE;
    :NEW.UPDATED_BY_USER := 'JOEMANAGER';

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error in TRIGGER_InsertLog');
END;
/

--Update Log
CREATE OR REPLACE TRIGGER TRIGGER_UpdateLog 
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF (:new.UPDATED_BY_USER != :old.UPDATED_BY_USER) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error in TRIGGER_UpdateLog');
    END IF;
END;
/

--Delete Log
CREATE OR REPLACE TRIGGER TRIGGER_DeleteLog
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF (:OLD.UPDATED_BY_USER != 'JOEMANAGER') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error only JOEMANAGER can delete TRIGGER_DeleteLog');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error in TRIGGER_DeleteLog');
END;
/

